version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
    groups:
      mantine:
        patterns:
          - "@mantine/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      inertia:
        patterns:
          - "@inertiajs/*"
      minor-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@mantine/*"
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
          - "@inertiajs/*"

  - package-ecosystem: composer
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
    groups:
      laravel:
        patterns:
          - "laravel/*"
          - "inertiajs/*"
      minor-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "laravel/*"
          - "inertiajs/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /deploy
    schedule:
      interval: weekly
