root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["node_modules", "tmp", "vendor", "public", "resources"]
  delay = 1000

[misc]
  clean_on_exit = true
