// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package db

import (
	"context"
)

const categoryHasSubscriptions = `-- name: CategoryHasSubscriptions :one
SELECT COUNT(*) FROM feed_subscriptions WHERE category_id = $1
`

func (q *Queries) CategoryHasSubscriptions(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRow(ctx, categoryHasSubscriptions, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO subscription_categories (user_id, name, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
RETURNING id, user_id, name, created_at, updated_at
`

type CreateCategoryParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (SubscriptionCategory, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.UserID, arg.Name)
	var i SubscriptionCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllCategoriesForUser = `-- name: DeleteAllCategoriesForUser :exec
DELETE FROM subscription_categories WHERE user_id = $1
`

func (q *Queries) DeleteAllCategoriesForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAllCategoriesForUser, userID)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM subscription_categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const findCategoryByID = `-- name: FindCategoryByID :one
SELECT id, user_id, name, created_at, updated_at
FROM subscription_categories WHERE id = $1
`

func (q *Queries) FindCategoryByID(ctx context.Context, id int64) (SubscriptionCategory, error) {
	row := q.db.QueryRow(ctx, findCategoryByID, id)
	var i SubscriptionCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOrCreateCategory = `-- name: FindOrCreateCategory :one
INSERT INTO subscription_categories (user_id, name, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
ON CONFLICT (user_id, name) DO UPDATE SET updated_at = NOW()
RETURNING id, user_id, name, created_at, updated_at
`

type FindOrCreateCategoryParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) FindOrCreateCategory(ctx context.Context, arg FindOrCreateCategoryParams) (SubscriptionCategory, error) {
	row := q.db.QueryRow(ctx, findOrCreateCategory, arg.UserID, arg.Name)
	var i SubscriptionCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoriesForUser = `-- name: ListCategoriesForUser :many
SELECT id, user_id, name, created_at, updated_at
FROM subscription_categories WHERE user_id = $1 ORDER BY name
`

func (q *Queries) ListCategoriesForUser(ctx context.Context, userID int64) ([]SubscriptionCategory, error) {
	rows, err := q.db.Query(ctx, listCategoriesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionCategory{}
	for rows.Next() {
		var i SubscriptionCategory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
