// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countForReader = `-- name: CountForReader :one
SELECT COUNT(*)
FROM entries e
JOIN feed_subscriptions fs ON e.feed_id = fs.feed_id AND fs.user_id = $1
LEFT JOIN entry_interactions ei ON e.id = ei.entry_id AND ei.user_id = $1
WHERE (ei.filtered_at IS NULL)
    AND ($2::bigint IS NULL OR e.feed_id = $2)
    AND ($3::bigint IS NULL OR fs.category_id = $3)
    AND (
        CASE $4::text
            WHEN 'unread' THEN ei.read_at IS NULL
            WHEN 'read' THEN ei.read_at IS NOT NULL
            WHEN 'favorites' THEN ei.starred_at IS NOT NULL
            ELSE TRUE
        END
    )
`

type CountForReaderParams struct {
	UserID     int64       `json:"user_id"`
	FeedID     pgtype.Int8 `json:"feed_id"`
	CategoryID pgtype.Int8 `json:"category_id"`
	Filter     string      `json:"filter"`
}

func (q *Queries) CountForReader(ctx context.Context, arg CountForReaderParams) (int64, error) {
	row := q.db.QueryRow(ctx, countForReader,
		arg.UserID,
		arg.FeedID,
		arg.CategoryID,
		arg.Filter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRead = `-- name: CountRead :one
SELECT COUNT(*)
FROM entries e
JOIN feed_subscriptions fs ON e.feed_id = fs.feed_id AND fs.user_id = $1
LEFT JOIN entry_interactions ei ON e.id = ei.entry_id AND ei.user_id = $1
WHERE (ei.filtered_at IS NULL) AND (ei.read_at IS NOT NULL)
`

func (q *Queries) CountRead(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRead, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnread = `-- name: CountUnread :one
SELECT COUNT(*)
FROM entries e
JOIN feed_subscriptions fs ON e.feed_id = fs.feed_id AND fs.user_id = $1
LEFT JOIN entry_interactions ei ON e.id = ei.entry_id AND ei.user_id = $1
WHERE (ei.filtered_at IS NULL) AND (ei.read_at IS NULL)
`

func (q *Queries) CountUnread(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnread, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const entriesForFeed = `-- name: EntriesForFeed :many
SELECT id, feed_id, title, url, author, content, published_at, created_at, updated_at
FROM entries WHERE feed_id = $1
`

func (q *Queries) EntriesForFeed(ctx context.Context, feedID int64) ([]Entry, error) {
	rows, err := q.db.Query(ctx, entriesForFeed, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.URL,
			&i.Author,
			&i.Content,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEntryByID = `-- name: FindEntryByID :one
SELECT id, feed_id, title, url, author, content, published_at, created_at, updated_at
FROM entries WHERE id = $1
`

func (q *Queries) FindEntryByID(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRow(ctx, findEntryByID, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.URL,
		&i.Author,
		&i.Content,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findReaderEntry = `-- name: FindReaderEntry :one
SELECT e.id, e.feed_id, e.title, e.url, e.author, e.content, e.published_at,
    ei.read_at, ei.starred_at, ei.archived_at, ei.filtered_at,
    f.name AS feed_name, fs.custom_feed_name, f.favicon_url, f.favicon_is_dark
FROM entries e
JOIN feed_subscriptions fs ON e.feed_id = fs.feed_id AND fs.user_id = $1
JOIN feeds f ON e.feed_id = f.id
LEFT JOIN entry_interactions ei ON e.id = ei.entry_id AND ei.user_id = $1
WHERE e.id = $2
`

type FindReaderEntryParams struct {
	UserID  int64 `json:"user_id"`
	EntryID int64 `json:"entry_id"`
}

type FindReaderEntryRow struct {
	ID             int64      `json:"id"`
	FeedID         int64      `json:"feed_id"`
	Title          string     `json:"title"`
	URL            string     `json:"url"`
	Author         *string    `json:"author"`
	Content        *string    `json:"content"`
	PublishedAt    time.Time  `json:"published_at"`
	ReadAt         *time.Time `json:"read_at"`
	StarredAt      *time.Time `json:"starred_at"`
	ArchivedAt     *time.Time `json:"archived_at"`
	FilteredAt     *time.Time `json:"filtered_at"`
	FeedName       string     `json:"feed_name"`
	CustomFeedName *string    `json:"custom_feed_name"`
	FaviconURL     *string    `json:"favicon_url"`
	FaviconIsDark  *bool      `json:"favicon_is_dark"`
}

func (q *Queries) FindReaderEntry(ctx context.Context, arg FindReaderEntryParams) (FindReaderEntryRow, error) {
	row := q.db.QueryRow(ctx, findReaderEntry, arg.UserID, arg.EntryID)
	var i FindReaderEntryRow
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.URL,
		&i.Author,
		&i.Content,
		&i.PublishedAt,
		&i.ReadAt,
		&i.StarredAt,
		&i.ArchivedAt,
		&i.FilteredAt,
		&i.FeedName,
		&i.CustomFeedName,
		&i.FaviconURL,
		&i.FaviconIsDark,
	)
	return i, err
}

const listForReaderByCreated = `-- name: ListForReaderByCreated :many
SELECT e.id, e.feed_id, e.title, e.url, e.author, e.content, e.published_at,
    ei.read_at, ei.starred_at, ei.archived_at, ei.filtered_at,
    f.name AS feed_name, fs.custom_feed_name, f.favicon_url, f.favicon_is_dark
FROM entries e
JOIN feed_subscriptions fs ON e.feed_id = fs.feed_id AND fs.user_id = $1
JOIN feeds f ON e.feed_id = f.id
LEFT JOIN entry_interactions ei ON e.id = ei.entry_id AND ei.user_id = $1
WHERE (ei.filtered_at IS NULL)
    AND ($2::bigint IS NULL OR e.feed_id = $2)
    AND ($3::bigint IS NULL OR fs.category_id = $3)
    AND (
        CASE $4::text
            WHEN 'unread' THEN ei.read_at IS NULL
            WHEN 'read' THEN ei.read_at IS NOT NULL
            WHEN 'favorites' THEN ei.starred_at IS NOT NULL
            ELSE TRUE
        END
    )
ORDER BY e.created_at DESC
LIMIT $6 OFFSET $5
`

type ListForReaderByCreatedParams struct {
	UserID     int64       `json:"user_id"`
	FeedID     pgtype.Int8 `json:"feed_id"`
	CategoryID pgtype.Int8 `json:"category_id"`
	Filter     string      `json:"filter"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

type ListForReaderByCreatedRow struct {
	ID             int64      `json:"id"`
	FeedID         int64      `json:"feed_id"`
	Title          string     `json:"title"`
	URL            string     `json:"url"`
	Author         *string    `json:"author"`
	Content        *string    `json:"content"`
	PublishedAt    time.Time  `json:"published_at"`
	ReadAt         *time.Time `json:"read_at"`
	StarredAt      *time.Time `json:"starred_at"`
	ArchivedAt     *time.Time `json:"archived_at"`
	FilteredAt     *time.Time `json:"filtered_at"`
	FeedName       string     `json:"feed_name"`
	CustomFeedName *string    `json:"custom_feed_name"`
	FaviconURL     *string    `json:"favicon_url"`
	FaviconIsDark  *bool      `json:"favicon_is_dark"`
}

func (q *Queries) ListForReaderByCreated(ctx context.Context, arg ListForReaderByCreatedParams) ([]ListForReaderByCreatedRow, error) {
	rows, err := q.db.Query(ctx, listForReaderByCreated,
		arg.UserID,
		arg.FeedID,
		arg.CategoryID,
		arg.Filter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListForReaderByCreatedRow{}
	for rows.Next() {
		var i ListForReaderByCreatedRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.URL,
			&i.Author,
			&i.Content,
			&i.PublishedAt,
			&i.ReadAt,
			&i.StarredAt,
			&i.ArchivedAt,
			&i.FilteredAt,
			&i.FeedName,
			&i.CustomFeedName,
			&i.FaviconURL,
			&i.FaviconIsDark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForReaderByPublished = `-- name: ListForReaderByPublished :many
SELECT e.id, e.feed_id, e.title, e.url, e.author, e.content, e.published_at,
    ei.read_at, ei.starred_at, ei.archived_at, ei.filtered_at,
    f.name AS feed_name, fs.custom_feed_name, f.favicon_url, f.favicon_is_dark
FROM entries e
JOIN feed_subscriptions fs ON e.feed_id = fs.feed_id AND fs.user_id = $1
JOIN feeds f ON e.feed_id = f.id
LEFT JOIN entry_interactions ei ON e.id = ei.entry_id AND ei.user_id = $1
WHERE (ei.filtered_at IS NULL)
    AND ($2::bigint IS NULL OR e.feed_id = $2)
    AND ($3::bigint IS NULL OR fs.category_id = $3)
    AND (
        CASE $4::text
            WHEN 'unread' THEN ei.read_at IS NULL
            WHEN 'read' THEN ei.read_at IS NOT NULL
            WHEN 'favorites' THEN ei.starred_at IS NOT NULL
            ELSE TRUE
        END
    )
ORDER BY e.published_at DESC
LIMIT $6 OFFSET $5
`

type ListForReaderByPublishedParams struct {
	UserID     int64       `json:"user_id"`
	FeedID     pgtype.Int8 `json:"feed_id"`
	CategoryID pgtype.Int8 `json:"category_id"`
	Filter     string      `json:"filter"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

type ListForReaderByPublishedRow struct {
	ID             int64      `json:"id"`
	FeedID         int64      `json:"feed_id"`
	Title          string     `json:"title"`
	URL            string     `json:"url"`
	Author         *string    `json:"author"`
	Content        *string    `json:"content"`
	PublishedAt    time.Time  `json:"published_at"`
	ReadAt         *time.Time `json:"read_at"`
	StarredAt      *time.Time `json:"starred_at"`
	ArchivedAt     *time.Time `json:"archived_at"`
	FilteredAt     *time.Time `json:"filtered_at"`
	FeedName       string     `json:"feed_name"`
	CustomFeedName *string    `json:"custom_feed_name"`
	FaviconURL     *string    `json:"favicon_url"`
	FaviconIsDark  *bool      `json:"favicon_is_dark"`
}

func (q *Queries) ListForReaderByPublished(ctx context.Context, arg ListForReaderByPublishedParams) ([]ListForReaderByPublishedRow, error) {
	rows, err := q.db.Query(ctx, listForReaderByPublished,
		arg.UserID,
		arg.FeedID,
		arg.CategoryID,
		arg.Filter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListForReaderByPublishedRow{}
	for rows.Next() {
		var i ListForReaderByPublishedRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.URL,
			&i.Author,
			&i.Content,
			&i.PublishedAt,
			&i.ReadAt,
			&i.StarredAt,
			&i.ArchivedAt,
			&i.FilteredAt,
			&i.FeedName,
			&i.CustomFeedName,
			&i.FaviconURL,
			&i.FaviconIsDark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
