// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFeedSubscribers = `-- name: CountFeedSubscribers :one
SELECT COUNT(*) FROM feed_subscriptions WHERE feed_id = $1
`

func (q *Queries) CountFeedSubscribers(ctx context.Context, feedID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFeedSubscribers, feedID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (name, feed_url, site_url, favicon_url, favicon_is_dark, favicon_updated_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
RETURNING id, name, feed_url, site_url, favicon_url, favicon_is_dark,
    favicon_updated_at, last_successful_refresh_at, last_failed_refresh_at,
    last_error_message, created_at, updated_at,
    etag, last_modified, is_gone, consecutive_failures, retry_after
`

type CreateFeedParams struct {
	Name             string     `json:"name"`
	FeedURL          string     `json:"feed_url"`
	SiteURL          string     `json:"site_url"`
	FaviconURL       *string    `json:"favicon_url"`
	FaviconIsDark    *bool      `json:"favicon_is_dark"`
	FaviconUpdatedAt *time.Time `json:"favicon_updated_at"`
	CreatedAt        *time.Time `json:"created_at"`
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRow(ctx, createFeed,
		arg.Name,
		arg.FeedURL,
		arg.SiteURL,
		arg.FaviconURL,
		arg.FaviconIsDark,
		arg.FaviconUpdatedAt,
		arg.CreatedAt,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FeedURL,
		&i.SiteURL,
		&i.FaviconURL,
		&i.FaviconIsDark,
		&i.FaviconUpdatedAt,
		&i.LastSuccessfulRefreshAt,
		&i.LastFailedRefreshAt,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ETag,
		&i.LastModified,
		&i.IsGone,
		&i.ConsecutiveFailures,
		&i.RetryAfter,
	)
	return i, err
}

const deleteFeed = `-- name: DeleteFeed :exec
DELETE FROM feeds WHERE id = $1
`

func (q *Queries) DeleteFeed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFeed, id)
	return err
}

const feedsMissingFavicons = `-- name: FeedsMissingFavicons :many
SELECT id, name, feed_url, site_url, favicon_url, favicon_is_dark,
    favicon_updated_at, last_successful_refresh_at, last_failed_refresh_at,
    last_error_message, created_at, updated_at,
    etag, last_modified, is_gone, consecutive_failures, retry_after
FROM feeds WHERE favicon_url IS NULL
`

func (q *Queries) FeedsMissingFavicons(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.Query(ctx, feedsMissingFavicons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FeedURL,
			&i.SiteURL,
			&i.FaviconURL,
			&i.FaviconIsDark,
			&i.FaviconUpdatedAt,
			&i.LastSuccessfulRefreshAt,
			&i.LastFailedRefreshAt,
			&i.LastErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ETag,
			&i.LastModified,
			&i.IsGone,
			&i.ConsecutiveFailures,
			&i.RetryAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const feedsNeedingRefresh = `-- name: FeedsNeedingRefresh :many
SELECT f.id, f.name, f.feed_url, f.site_url, f.favicon_url, f.favicon_is_dark,
    f.favicon_updated_at, f.last_successful_refresh_at, f.last_failed_refresh_at,
    f.last_error_message, f.created_at, f.updated_at,
    f.etag, f.last_modified, f.is_gone, f.consecutive_failures, f.retry_after
FROM feeds f
JOIN feed_subscriptions fs ON fs.feed_id = f.id
WHERE f.is_gone = FALSE
    AND (f.retry_after IS NULL OR f.retry_after <= NOW())
    AND (
        GREATEST(f.last_successful_refresh_at, f.last_failed_refresh_at) IS NULL
        OR GREATEST(f.last_successful_refresh_at, f.last_failed_refresh_at) < NOW() - $1::interval
    )
GROUP BY f.id
ORDER BY
    CASE WHEN GREATEST(f.last_successful_refresh_at, f.last_failed_refresh_at) IS NULL THEN 0
    ELSE EXTRACT(EPOCH FROM NOW() - GREATEST(f.last_successful_refresh_at, f.last_failed_refresh_at))
        / GREATEST(EXTRACT(EPOCH FROM NOW() - COALESCE(
            (SELECT MAX(e.published_at) FROM entries e WHERE e.feed_id = f.id),
            f.created_at - INTERVAL '3650 days'
        )), 1)
    END DESC
LIMIT $2
`

type FeedsNeedingRefreshParams struct {
	StaleAfter pgtype.Interval `json:"stale_after"`
	MaxFeeds   int32           `json:"max_feeds"`
}

func (q *Queries) FeedsNeedingRefresh(ctx context.Context, arg FeedsNeedingRefreshParams) ([]Feed, error) {
	rows, err := q.db.Query(ctx, feedsNeedingRefresh, arg.StaleAfter, arg.MaxFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FeedURL,
			&i.SiteURL,
			&i.FaviconURL,
			&i.FaviconIsDark,
			&i.FaviconUpdatedAt,
			&i.LastSuccessfulRefreshAt,
			&i.LastFailedRefreshAt,
			&i.LastErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ETag,
			&i.LastModified,
			&i.IsGone,
			&i.ConsecutiveFailures,
			&i.RetryAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const feedsWithOutdatedFavicons = `-- name: FeedsWithOutdatedFavicons :many
SELECT id, name, feed_url, site_url, favicon_url, favicon_is_dark,
    favicon_updated_at, last_successful_refresh_at, last_failed_refresh_at,
    last_error_message, created_at, updated_at,
    etag, last_modified, is_gone, consecutive_failures, retry_after
FROM feeds
WHERE favicon_url IS NULL
    OR favicon_updated_at IS NULL
    OR favicon_updated_at < NOW() - $1::interval
`

func (q *Queries) FeedsWithOutdatedFavicons(ctx context.Context, olderThan pgtype.Interval) ([]Feed, error) {
	rows, err := q.db.Query(ctx, feedsWithOutdatedFavicons, olderThan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FeedURL,
			&i.SiteURL,
			&i.FaviconURL,
			&i.FaviconIsDark,
			&i.FaviconUpdatedAt,
			&i.LastSuccessfulRefreshAt,
			&i.LastFailedRefreshAt,
			&i.LastErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ETag,
			&i.LastModified,
			&i.IsGone,
			&i.ConsecutiveFailures,
			&i.RetryAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFeedByID = `-- name: FindFeedByID :one
SELECT id, name, feed_url, site_url, favicon_url, favicon_is_dark,
    favicon_updated_at, last_successful_refresh_at, last_failed_refresh_at,
    last_error_message, created_at, updated_at,
    etag, last_modified, is_gone, consecutive_failures, retry_after
FROM feeds WHERE id = $1
`

func (q *Queries) FindFeedByID(ctx context.Context, id int64) (Feed, error) {
	row := q.db.QueryRow(ctx, findFeedByID, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FeedURL,
		&i.SiteURL,
		&i.FaviconURL,
		&i.FaviconIsDark,
		&i.FaviconUpdatedAt,
		&i.LastSuccessfulRefreshAt,
		&i.LastFailedRefreshAt,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ETag,
		&i.LastModified,
		&i.IsGone,
		&i.ConsecutiveFailures,
		&i.RetryAfter,
	)
	return i, err
}

const findFeedByURL = `-- name: FindFeedByURL :one
SELECT id, name, feed_url, site_url, favicon_url, favicon_is_dark,
    favicon_updated_at, last_successful_refresh_at, last_failed_refresh_at,
    last_error_message, created_at, updated_at,
    etag, last_modified, is_gone, consecutive_failures, retry_after
FROM feeds WHERE feed_url = $1
`

func (q *Queries) FindFeedByURL(ctx context.Context, feedUrl string) (Feed, error) {
	row := q.db.QueryRow(ctx, findFeedByURL, feedUrl)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FeedURL,
		&i.SiteURL,
		&i.FaviconURL,
		&i.FaviconIsDark,
		&i.FaviconUpdatedAt,
		&i.LastSuccessfulRefreshAt,
		&i.LastFailedRefreshAt,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ETag,
		&i.LastModified,
		&i.IsGone,
		&i.ConsecutiveFailures,
		&i.RetryAfter,
	)
	return i, err
}

const updateFeedFavicon = `-- name: UpdateFeedFavicon :exec
UPDATE feeds SET favicon_url = $2, favicon_is_dark = $3, favicon_updated_at = NOW(), updated_at = NOW()
WHERE id = $1
`

type UpdateFeedFaviconParams struct {
	ID            int64   `json:"id"`
	FaviconURL    *string `json:"favicon_url"`
	FaviconIsDark *bool   `json:"favicon_is_dark"`
}

func (q *Queries) UpdateFeedFavicon(ctx context.Context, arg UpdateFeedFaviconParams) error {
	_, err := q.db.Exec(ctx, updateFeedFavicon, arg.ID, arg.FaviconURL, arg.FaviconIsDark)
	return err
}

const updateFeedGone = `-- name: UpdateFeedGone :exec
UPDATE feeds SET is_gone = TRUE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateFeedGone(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateFeedGone, id)
	return err
}

const updateFeedRefreshFailure = `-- name: UpdateFeedRefreshFailure :exec
UPDATE feeds SET last_failed_refresh_at = NOW(), last_error_message = $2,
    consecutive_failures = consecutive_failures + 1,
    retry_after = NOW() + LEAST(15 * POWER(2, consecutive_failures), 480) * INTERVAL '1 minute',
    updated_at = NOW()
WHERE id = $1
`

type UpdateFeedRefreshFailureParams struct {
	ID               int64   `json:"id"`
	LastErrorMessage *string `json:"last_error_message"`
}

func (q *Queries) UpdateFeedRefreshFailure(ctx context.Context, arg UpdateFeedRefreshFailureParams) error {
	_, err := q.db.Exec(ctx, updateFeedRefreshFailure, arg.ID, arg.LastErrorMessage)
	return err
}

const updateFeedRefreshSuccess = `-- name: UpdateFeedRefreshSuccess :exec
UPDATE feeds SET last_successful_refresh_at = NOW(), last_error_message = NULL,
    etag = $2, last_modified = $3,
    consecutive_failures = 0, retry_after = NULL, updated_at = NOW()
WHERE id = $1
`

type UpdateFeedRefreshSuccessParams struct {
	ID           int64   `json:"id"`
	ETag         *string `json:"etag"`
	LastModified *string `json:"last_modified"`
}

func (q *Queries) UpdateFeedRefreshSuccess(ctx context.Context, arg UpdateFeedRefreshSuccessParams) error {
	_, err := q.db.Exec(ctx, updateFeedRefreshSuccess, arg.ID, arg.ETag, arg.LastModified)
	return err
}

const updateFeedRetryAfter = `-- name: UpdateFeedRetryAfter :exec
UPDATE feeds SET retry_after = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateFeedRetryAfterParams struct {
	ID         int64      `json:"id"`
	RetryAfter *time.Time `json:"retry_after"`
}

func (q *Queries) UpdateFeedRetryAfter(ctx context.Context, arg UpdateFeedRetryAfterParams) error {
	_, err := q.db.Exec(ctx, updateFeedRetryAfter, arg.ID, arg.RetryAfter)
	return err
}
