// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interactions.sql

package db

import (
	"context"
)

const archive = `-- name: Archive :exec
INSERT INTO entry_interactions (user_id, entry_id, archived_at, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW(), NOW())
ON CONFLICT (user_id, entry_id) DO UPDATE SET archived_at = NOW(), updated_at = NOW()
`

type ArchiveParams struct {
	UserID  int64 `json:"user_id"`
	EntryID int64 `json:"entry_id"`
}

func (q *Queries) Archive(ctx context.Context, arg ArchiveParams) error {
	_, err := q.db.Exec(ctx, archive, arg.UserID, arg.EntryID)
	return err
}

const clearFiltered = `-- name: ClearFiltered :exec
INSERT INTO entry_interactions (user_id, entry_id, filtered_at, created_at, updated_at)
VALUES ($1, $2, NULL, NOW(), NOW())
ON CONFLICT (user_id, entry_id) DO UPDATE SET filtered_at = NULL, updated_at = NOW()
`

type ClearFilteredParams struct {
	UserID  int64 `json:"user_id"`
	EntryID int64 `json:"entry_id"`
}

func (q *Queries) ClearFiltered(ctx context.Context, arg ClearFilteredParams) error {
	_, err := q.db.Exec(ctx, clearFiltered, arg.UserID, arg.EntryID)
	return err
}

const deleteAllInteractionsForUser = `-- name: DeleteAllInteractionsForUser :exec
DELETE FROM entry_interactions WHERE user_id = $1
`

func (q *Queries) DeleteAllInteractionsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAllInteractionsForUser, userID)
	return err
}

const deleteInteractionsForFeed = `-- name: DeleteInteractionsForFeed :exec
DELETE FROM entry_interactions
WHERE user_id = $1 AND entry_id IN (
    SELECT id FROM entries WHERE feed_id = $2
)
`

type DeleteInteractionsForFeedParams struct {
	UserID int64 `json:"user_id"`
	FeedID int64 `json:"feed_id"`
}

func (q *Queries) DeleteInteractionsForFeed(ctx context.Context, arg DeleteInteractionsForFeedParams) error {
	_, err := q.db.Exec(ctx, deleteInteractionsForFeed, arg.UserID, arg.FeedID)
	return err
}

const favorite = `-- name: Favorite :exec
INSERT INTO entry_interactions (user_id, entry_id, starred_at, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW(), NOW())
ON CONFLICT (user_id, entry_id) DO UPDATE SET starred_at = NOW(), updated_at = NOW()
`

type FavoriteParams struct {
	UserID  int64 `json:"user_id"`
	EntryID int64 `json:"entry_id"`
}

func (q *Queries) Favorite(ctx context.Context, arg FavoriteParams) error {
	_, err := q.db.Exec(ctx, favorite, arg.UserID, arg.EntryID)
	return err
}

const markAllAsReadExisting = `-- name: MarkAllAsReadExisting :exec
UPDATE entry_interactions SET read_at = NOW(), updated_at = NOW()
WHERE user_id = $1 AND entry_id IN (
    SELECT e.id FROM entries e WHERE e.feed_id = $2
) AND read_at IS NULL
`

type MarkAllAsReadExistingParams struct {
	UserID int64 `json:"user_id"`
	FeedID int64 `json:"feed_id"`
}

func (q *Queries) MarkAllAsReadExisting(ctx context.Context, arg MarkAllAsReadExistingParams) error {
	_, err := q.db.Exec(ctx, markAllAsReadExisting, arg.UserID, arg.FeedID)
	return err
}

const markAllAsReadNew = `-- name: MarkAllAsReadNew :exec
INSERT INTO entry_interactions (user_id, entry_id, read_at, created_at, updated_at)
SELECT $1, e.id, NOW(), NOW(), NOW()
FROM entries e
WHERE e.feed_id = $2
    AND NOT EXISTS (
        SELECT 1 FROM entry_interactions ei WHERE ei.user_id = $1 AND ei.entry_id = e.id
    )
`

type MarkAllAsReadNewParams struct {
	UserID int64 `json:"user_id"`
	FeedID int64 `json:"feed_id"`
}

func (q *Queries) MarkAllAsReadNew(ctx context.Context, arg MarkAllAsReadNewParams) error {
	_, err := q.db.Exec(ctx, markAllAsReadNew, arg.UserID, arg.FeedID)
	return err
}

const markAsRead = `-- name: MarkAsRead :exec
INSERT INTO entry_interactions (user_id, entry_id, read_at, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW(), NOW())
ON CONFLICT (user_id, entry_id) DO UPDATE SET read_at = NOW(), updated_at = NOW()
`

type MarkAsReadParams struct {
	UserID  int64 `json:"user_id"`
	EntryID int64 `json:"entry_id"`
}

func (q *Queries) MarkAsRead(ctx context.Context, arg MarkAsReadParams) error {
	_, err := q.db.Exec(ctx, markAsRead, arg.UserID, arg.EntryID)
	return err
}

const markAsUnread = `-- name: MarkAsUnread :exec
INSERT INTO entry_interactions (user_id, entry_id, read_at, created_at, updated_at)
VALUES ($1, $2, NULL, NOW(), NOW())
ON CONFLICT (user_id, entry_id) DO UPDATE SET read_at = NULL, updated_at = NOW()
`

type MarkAsUnreadParams struct {
	UserID  int64 `json:"user_id"`
	EntryID int64 `json:"entry_id"`
}

func (q *Queries) MarkAsUnread(ctx context.Context, arg MarkAsUnreadParams) error {
	_, err := q.db.Exec(ctx, markAsUnread, arg.UserID, arg.EntryID)
	return err
}

const markFiltered = `-- name: MarkFiltered :exec
INSERT INTO entry_interactions (user_id, entry_id, filtered_at, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW(), NOW())
ON CONFLICT (user_id, entry_id) DO UPDATE SET
    filtered_at = NOW(),
    read_at = NULL,
    starred_at = NULL,
    archived_at = NULL,
    updated_at = NOW()
`

type MarkFilteredParams struct {
	UserID  int64 `json:"user_id"`
	EntryID int64 `json:"entry_id"`
}

func (q *Queries) MarkFiltered(ctx context.Context, arg MarkFilteredParams) error {
	_, err := q.db.Exec(ctx, markFiltered, arg.UserID, arg.EntryID)
	return err
}

const starredIDs = `-- name: StarredIDs :many
SELECT ei.entry_id FROM entry_interactions ei
JOIN feed_subscriptions fs ON ei.entry_id IN (
    SELECT id FROM entries WHERE feed_id = fs.feed_id
) AND fs.user_id = $1
WHERE ei.user_id = $1 AND ei.starred_at IS NOT NULL
`

func (q *Queries) StarredIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, starredIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var entry_id int64
		if err := rows.Scan(&entry_id); err != nil {
			return nil, err
		}
		items = append(items, entry_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchive = `-- name: Unarchive :exec
INSERT INTO entry_interactions (user_id, entry_id, archived_at, created_at, updated_at)
VALUES ($1, $2, NULL, NOW(), NOW())
ON CONFLICT (user_id, entry_id) DO UPDATE SET archived_at = NULL, updated_at = NOW()
`

type UnarchiveParams struct {
	UserID  int64 `json:"user_id"`
	EntryID int64 `json:"entry_id"`
}

func (q *Queries) Unarchive(ctx context.Context, arg UnarchiveParams) error {
	_, err := q.db.Exec(ctx, unarchive, arg.UserID, arg.EntryID)
	return err
}

const unfavorite = `-- name: Unfavorite :exec
INSERT INTO entry_interactions (user_id, entry_id, starred_at, created_at, updated_at)
VALUES ($1, $2, NULL, NOW(), NOW())
ON CONFLICT (user_id, entry_id) DO UPDATE SET starred_at = NULL, updated_at = NOW()
`

type UnfavoriteParams struct {
	UserID  int64 `json:"user_id"`
	EntryID int64 `json:"entry_id"`
}

func (q *Queries) Unfavorite(ctx context.Context, arg UnfavoriteParams) error {
	_, err := q.db.Exec(ctx, unfavorite, arg.UserID, arg.EntryID)
	return err
}

const unreadIDs = `-- name: UnreadIDs :many
SELECT e.id FROM entries e
JOIN feed_subscriptions fs ON e.feed_id = fs.feed_id AND fs.user_id = $1
LEFT JOIN entry_interactions ei ON e.id = ei.entry_id AND ei.user_id = $1
WHERE ei.read_at IS NULL AND (ei.filtered_at IS NULL)
`

func (q *Queries) UnreadIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, unreadIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
