// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refreshes.sql

package db

import (
	"context"
	"time"
)

const getRefreshStats = `-- name: GetRefreshStats :one
SELECT
    COUNT(*) FILTER (WHERE fr.was_successful) AS successes,
    COUNT(*) FILTER (WHERE NOT fr.was_successful) AS failures,
    COALESCE(SUM(fr.entries_created) FILTER (WHERE fr.was_successful), 0)::bigint AS entries_created
FROM feed_refreshes fr
JOIN feed_subscriptions fs ON fr.feed_id = fs.feed_id AND fs.user_id = $1
WHERE fr.refreshed_at >= $2
`

type GetRefreshStatsParams struct {
	UserID      int64     `json:"user_id"`
	RefreshedAt time.Time `json:"refreshed_at"`
}

type GetRefreshStatsRow struct {
	Successes      int64 `json:"successes"`
	Failures       int64 `json:"failures"`
	EntriesCreated int64 `json:"entries_created"`
}

func (q *Queries) GetRefreshStats(ctx context.Context, arg GetRefreshStatsParams) (GetRefreshStatsRow, error) {
	row := q.db.QueryRow(ctx, getRefreshStats, arg.UserID, arg.RefreshedAt)
	var i GetRefreshStatsRow
	err := row.Scan(&i.Successes, &i.Failures, &i.EntriesCreated)
	return i, err
}

const listFeedRefreshes = `-- name: ListFeedRefreshes :many
SELECT id, feed_id, refreshed_at, was_successful, entries_created, error_message, created_at, updated_at
FROM feed_refreshes WHERE feed_id = $1
ORDER BY refreshed_at DESC LIMIT 20
`

func (q *Queries) ListFeedRefreshes(ctx context.Context, feedID int64) ([]FeedRefresh, error) {
	rows, err := q.db.Query(ctx, listFeedRefreshes, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeedRefresh{}
	for rows.Next() {
		var i FeedRefresh
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.RefreshedAt,
			&i.WasSuccessful,
			&i.EntriesCreated,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordRefresh = `-- name: RecordRefresh :exec
INSERT INTO feed_refreshes (feed_id, refreshed_at, was_successful, entries_created, error_message, created_at, updated_at)
VALUES ($1, NOW(), $2, $3, $4, NOW(), NOW())
`

type RecordRefreshParams struct {
	FeedID         int64   `json:"feed_id"`
	WasSuccessful  bool    `json:"was_successful"`
	EntriesCreated *int    `json:"entries_created"`
	ErrorMessage   *string `json:"error_message"`
}

func (q *Queries) RecordRefresh(ctx context.Context, arg RecordRefreshParams) error {
	_, err := q.db.Exec(ctx, recordRefresh,
		arg.FeedID,
		arg.WasSuccessful,
		arg.EntriesCreated,
		arg.ErrorMessage,
	)
	return err
}
