// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	Archive(ctx context.Context, arg ArchiveParams) error
	CacheGet(ctx context.Context, key string) (CacheGetRow, error)
	CacheSet(ctx context.Context, arg CacheSetParams) error
	CategoryHasSubscriptions(ctx context.Context, categoryID int64) (int64, error)
	ClearFiltered(ctx context.Context, arg ClearFilteredParams) error
	ClearUserEmailVerification(ctx context.Context, id int64) error
	CountFeedSubscribers(ctx context.Context, feedID int64) (int64, error)
	CountForReader(ctx context.Context, arg CountForReaderParams) (int64, error)
	CountRead(ctx context.Context, userID int64) (int64, error)
	CountUnread(ctx context.Context, userID int64) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (SubscriptionCategory, error)
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error
	CreatePersonalAccessToken(ctx context.Context, arg CreatePersonalAccessTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllCategoriesForUser(ctx context.Context, userID int64) error
	DeleteAllInteractionsForUser(ctx context.Context, userID int64) error
	DeleteAllSubscriptionsForUser(ctx context.Context, userID int64) error
	DeleteCategory(ctx context.Context, id int64) error
	DeleteFeed(ctx context.Context, id int64) error
	DeleteInteractionsForFeed(ctx context.Context, arg DeleteInteractionsForFeedParams) error
	DeletePasswordReset(ctx context.Context, email string) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserTokens(ctx context.Context, arg DeleteUserTokensParams) error
	EntriesForFeed(ctx context.Context, feedID int64) ([]Entry, error)
	EntryURLsForFeed(ctx context.Context, feedID int64) ([]string, error)
	Favorite(ctx context.Context, arg FavoriteParams) error
	FeedsMissingFavicons(ctx context.Context) ([]Feed, error)
	FeedsNeedingRefresh(ctx context.Context, arg FeedsNeedingRefreshParams) ([]Feed, error)
	FeedsWithOutdatedFavicons(ctx context.Context, olderThan pgtype.Interval) ([]Feed, error)
	FindCategoryByID(ctx context.Context, id int64) (SubscriptionCategory, error)
	FindEntryByID(ctx context.Context, id int64) (Entry, error)
	FindFeedByID(ctx context.Context, id int64) (Feed, error)
	FindFeedByURL(ctx context.Context, feedUrl string) (Feed, error)
	FindOrCreateCategory(ctx context.Context, arg FindOrCreateCategoryParams) (SubscriptionCategory, error)
	FindPasswordReset(ctx context.Context, email string) (PasswordResetToken, error)
	FindPersonalAccessToken(ctx context.Context, token string) (PersonalAccessToken, error)
	FindReaderEntry(ctx context.Context, arg FindReaderEntryParams) (FindReaderEntryRow, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByFeverApiKey(ctx context.Context, feverApiKey *string) (User, error)
	FindUserByID(ctx context.Context, id int64) (User, error)
	GetRefreshStats(ctx context.Context, arg GetRefreshStatsParams) (GetRefreshStatsRow, error)
	GetSubscription(ctx context.Context, arg GetSubscriptionParams) (FeedSubscription, error)
	ListCategoriesForUser(ctx context.Context, userID int64) ([]SubscriptionCategory, error)
	ListFeedIDsForUser(ctx context.Context, userID int64) ([]int64, error)
	ListFeedRefreshes(ctx context.Context, feedID int64) ([]FeedRefresh, error)
	ListForReaderByCreated(ctx context.Context, arg ListForReaderByCreatedParams) ([]ListForReaderByCreatedRow, error)
	ListForReaderByPublished(ctx context.Context, arg ListForReaderByPublishedParams) ([]ListForReaderByPublishedRow, error)
	ListSubscriptionsForUser(ctx context.Context, userID int64) ([]ListSubscriptionsForUserRow, error)
	MarkAllAsReadExisting(ctx context.Context, arg MarkAllAsReadExistingParams) error
	MarkAllAsReadNew(ctx context.Context, arg MarkAllAsReadNewParams) error
	MarkAsRead(ctx context.Context, arg MarkAsReadParams) error
	MarkAsUnread(ctx context.Context, arg MarkAsUnreadParams) error
	MarkFiltered(ctx context.Context, arg MarkFilteredParams) error
	RecordRefresh(ctx context.Context, arg RecordRefreshParams) error
	StarredIDs(ctx context.Context, userID int64) ([]int64, error)
	Subscribe(ctx context.Context, arg SubscribeParams) error
	SubscriptionsWithFilters(ctx context.Context, feedID int64) ([]FeedSubscription, error)
	TouchTokenLastUsed(ctx context.Context, id int64) error
	Unarchive(ctx context.Context, arg UnarchiveParams) error
	Unfavorite(ctx context.Context, arg UnfavoriteParams) error
	UnreadIDs(ctx context.Context, userID int64) ([]int64, error)
	Unsubscribe(ctx context.Context, arg UnsubscribeParams) error
	UpdateFeedFavicon(ctx context.Context, arg UpdateFeedFaviconParams) error
	UpdateFeedGone(ctx context.Context, id int64) error
	UpdateFeedRefreshFailure(ctx context.Context, arg UpdateFeedRefreshFailureParams) error
	UpdateFeedRefreshSuccess(ctx context.Context, arg UpdateFeedRefreshSuccessParams) error
	UpdateFeedRetryAfter(ctx context.Context, arg UpdateFeedRetryAfterParams) error
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserPasswordAndFeverKey(ctx context.Context, arg UpdateUserPasswordAndFeverKeyParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpdateUserTwoFactor(ctx context.Context, arg UpdateUserTwoFactorParams) error
	VerifyUserEmail(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
