// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const deleteAllSubscriptionsForUser = `-- name: DeleteAllSubscriptionsForUser :exec
DELETE FROM feed_subscriptions WHERE user_id = $1
`

func (q *Queries) DeleteAllSubscriptionsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAllSubscriptionsForUser, userID)
	return err
}

const getSubscription = `-- name: GetSubscription :one
SELECT user_id, feed_id, category_id, custom_feed_name, filter_rules, created_at, updated_at
FROM feed_subscriptions WHERE user_id = $1 AND feed_id = $2
`

type GetSubscriptionParams struct {
	UserID int64 `json:"user_id"`
	FeedID int64 `json:"feed_id"`
}

func (q *Queries) GetSubscription(ctx context.Context, arg GetSubscriptionParams) (FeedSubscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, arg.UserID, arg.FeedID)
	var i FeedSubscription
	err := row.Scan(
		&i.UserID,
		&i.FeedID,
		&i.CategoryID,
		&i.CustomFeedName,
		&i.FilterRules,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFeedIDsForUser = `-- name: ListFeedIDsForUser :many
SELECT feed_id FROM feed_subscriptions WHERE user_id = $1
`

func (q *Queries) ListFeedIDsForUser(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listFeedIDsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var feed_id int64
		if err := rows.Scan(&feed_id); err != nil {
			return nil, err
		}
		items = append(items, feed_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsForUser = `-- name: ListSubscriptionsForUser :many
SELECT f.id, f.name, f.feed_url, f.site_url, f.favicon_url, f.favicon_is_dark,
    f.favicon_updated_at, f.last_successful_refresh_at, f.last_failed_refresh_at,
    f.last_error_message, f.created_at, f.updated_at,
    fs.custom_feed_name, fs.category_id, sc.name as category_name, fs.filter_rules,
    COUNT(e.id)::bigint as entry_count,
    COUNT(e.id) FILTER (WHERE ei.read_at IS NULL AND ei.filtered_at IS NULL)::bigint as unread_count
FROM feeds f
JOIN feed_subscriptions fs ON f.id = fs.feed_id AND fs.user_id = $1
JOIN subscription_categories sc ON fs.category_id = sc.id
LEFT JOIN entries e ON f.id = e.feed_id
LEFT JOIN entry_interactions ei ON e.id = ei.entry_id AND ei.user_id = $1
GROUP BY f.id, fs.custom_feed_name, fs.category_id, sc.name, fs.filter_rules
ORDER BY COALESCE(fs.custom_feed_name, f.name)
`

type ListSubscriptionsForUserRow struct {
	ID                      int64           `json:"id"`
	Name                    string          `json:"name"`
	FeedURL                 string          `json:"feed_url"`
	SiteURL                 string          `json:"site_url"`
	FaviconURL              *string         `json:"favicon_url"`
	FaviconIsDark           *bool           `json:"favicon_is_dark"`
	FaviconUpdatedAt        *time.Time      `json:"favicon_updated_at"`
	LastSuccessfulRefreshAt *time.Time      `json:"last_successful_refresh_at"`
	LastFailedRefreshAt     *time.Time      `json:"last_failed_refresh_at"`
	LastErrorMessage        *string         `json:"last_error_message"`
	CreatedAt               *time.Time      `json:"created_at"`
	UpdatedAt               *time.Time      `json:"updated_at"`
	CustomFeedName          *string         `json:"custom_feed_name"`
	CategoryID              int64           `json:"category_id"`
	CategoryName            string          `json:"category_name"`
	FilterRules             json.RawMessage `json:"filter_rules"`
	EntryCount              int64           `json:"entry_count"`
	UnreadCount             int64           `json:"unread_count"`
}

func (q *Queries) ListSubscriptionsForUser(ctx context.Context, userID int64) ([]ListSubscriptionsForUserRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionsForUserRow{}
	for rows.Next() {
		var i ListSubscriptionsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FeedURL,
			&i.SiteURL,
			&i.FaviconURL,
			&i.FaviconIsDark,
			&i.FaviconUpdatedAt,
			&i.LastSuccessfulRefreshAt,
			&i.LastFailedRefreshAt,
			&i.LastErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomFeedName,
			&i.CategoryID,
			&i.CategoryName,
			&i.FilterRules,
			&i.EntryCount,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscribe = `-- name: Subscribe :exec
INSERT INTO feed_subscriptions (user_id, feed_id, category_id, custom_feed_name, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
ON CONFLICT (user_id, feed_id) DO NOTHING
`

type SubscribeParams struct {
	UserID         int64   `json:"user_id"`
	FeedID         int64   `json:"feed_id"`
	CategoryID     int64   `json:"category_id"`
	CustomFeedName *string `json:"custom_feed_name"`
}

func (q *Queries) Subscribe(ctx context.Context, arg SubscribeParams) error {
	_, err := q.db.Exec(ctx, subscribe,
		arg.UserID,
		arg.FeedID,
		arg.CategoryID,
		arg.CustomFeedName,
	)
	return err
}

const subscriptionsWithFilters = `-- name: SubscriptionsWithFilters :many
SELECT user_id, feed_id, category_id, custom_feed_name, filter_rules, created_at, updated_at
FROM feed_subscriptions WHERE feed_id = $1 AND filter_rules IS NOT NULL
`

func (q *Queries) SubscriptionsWithFilters(ctx context.Context, feedID int64) ([]FeedSubscription, error) {
	rows, err := q.db.Query(ctx, subscriptionsWithFilters, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeedSubscription{}
	for rows.Next() {
		var i FeedSubscription
		if err := rows.Scan(
			&i.UserID,
			&i.FeedID,
			&i.CategoryID,
			&i.CustomFeedName,
			&i.FilterRules,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsubscribe = `-- name: Unsubscribe :exec
DELETE FROM feed_subscriptions WHERE user_id = $1 AND feed_id = $2
`

type UnsubscribeParams struct {
	UserID int64 `json:"user_id"`
	FeedID int64 `json:"feed_id"`
}

func (q *Queries) Unsubscribe(ctx context.Context, arg UnsubscribeParams) error {
	_, err := q.db.Exec(ctx, unsubscribe, arg.UserID, arg.FeedID)
	return err
}

const updateSubscription = `-- name: UpdateSubscription :exec
UPDATE feed_subscriptions
SET category_id = $3, custom_feed_name = $4, filter_rules = $5, updated_at = NOW()
WHERE user_id = $1 AND feed_id = $2
`

type UpdateSubscriptionParams struct {
	UserID         int64           `json:"user_id"`
	FeedID         int64           `json:"feed_id"`
	CategoryID     int64           `json:"category_id"`
	CustomFeedName *string         `json:"custom_feed_name"`
	FilterRules    json.RawMessage `json:"filter_rules"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, updateSubscription,
		arg.UserID,
		arg.FeedID,
		arg.CategoryID,
		arg.CustomFeedName,
		arg.FilterRules,
	)
	return err
}
