// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package db

import (
	"context"
)

const cacheGet = `-- name: CacheGet :one
SELECT value, expiration FROM cache WHERE key = $1
`

type CacheGetRow struct {
	Value      string `json:"value"`
	Expiration int    `json:"expiration"`
}

func (q *Queries) CacheGet(ctx context.Context, key string) (CacheGetRow, error) {
	row := q.db.QueryRow(ctx, cacheGet, key)
	var i CacheGetRow
	err := row.Scan(&i.Value, &i.Expiration)
	return i, err
}

const cacheSet = `-- name: CacheSet :exec
INSERT INTO cache (key, value, expiration) VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE SET value = $2, expiration = $3
`

type CacheSetParams struct {
	Key        string `json:"key"`
	Value      string `json:"value"`
	Expiration int    `json:"expiration"`
}

func (q *Queries) CacheSet(ctx context.Context, arg CacheSetParams) error {
	_, err := q.db.Exec(ctx, cacheSet, arg.Key, arg.Value, arg.Expiration)
	return err
}

const createPasswordReset = `-- name: CreatePasswordReset :exec
INSERT INTO password_reset_tokens (email, token, created_at)
VALUES ($1, $2, NOW())
ON CONFLICT (email) DO UPDATE SET token = $2, created_at = NOW()
`

type CreatePasswordResetParams struct {
	Email string `json:"email"`
	Token string `json:"token"`
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error {
	_, err := q.db.Exec(ctx, createPasswordReset, arg.Email, arg.Token)
	return err
}

const createPersonalAccessToken = `-- name: CreatePersonalAccessToken :exec
INSERT INTO personal_access_tokens (tokenable_type, tokenable_id, name, token, abilities, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
`

type CreatePersonalAccessTokenParams struct {
	TokenableType string  `json:"tokenable_type"`
	TokenableID   int64   `json:"tokenable_id"`
	Name          string  `json:"name"`
	Token         string  `json:"token"`
	Abilities     *string `json:"abilities"`
}

func (q *Queries) CreatePersonalAccessToken(ctx context.Context, arg CreatePersonalAccessTokenParams) error {
	_, err := q.db.Exec(ctx, createPersonalAccessToken,
		arg.TokenableType,
		arg.TokenableID,
		arg.Name,
		arg.Token,
		arg.Abilities,
	)
	return err
}

const deletePasswordReset = `-- name: DeletePasswordReset :exec
DELETE FROM password_reset_tokens WHERE email = $1
`

func (q *Queries) DeletePasswordReset(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deletePasswordReset, email)
	return err
}

const deleteUserTokens = `-- name: DeleteUserTokens :exec
DELETE FROM personal_access_tokens
WHERE tokenable_type = $1 AND tokenable_id = $2
`

type DeleteUserTokensParams struct {
	TokenableType string `json:"tokenable_type"`
	TokenableID   int64  `json:"tokenable_id"`
}

func (q *Queries) DeleteUserTokens(ctx context.Context, arg DeleteUserTokensParams) error {
	_, err := q.db.Exec(ctx, deleteUserTokens, arg.TokenableType, arg.TokenableID)
	return err
}

const findPasswordReset = `-- name: FindPasswordReset :one
SELECT email, token, created_at FROM password_reset_tokens WHERE email = $1
`

func (q *Queries) FindPasswordReset(ctx context.Context, email string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, findPasswordReset, email)
	var i PasswordResetToken
	err := row.Scan(&i.Email, &i.Token, &i.CreatedAt)
	return i, err
}

const findPersonalAccessToken = `-- name: FindPersonalAccessToken :one
SELECT id, tokenable_type, tokenable_id, name, token, abilities,
    last_used_at, expires_at, created_at, updated_at
FROM personal_access_tokens WHERE token = $1
`

func (q *Queries) FindPersonalAccessToken(ctx context.Context, token string) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, findPersonalAccessToken, token)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenableType,
		&i.TokenableID,
		&i.Name,
		&i.Token,
		&i.Abilities,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchTokenLastUsed = `-- name: TouchTokenLastUsed :exec
UPDATE personal_access_tokens SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) TouchTokenLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchTokenLastUsed, id)
	return err
}
