// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"time"
)

const clearUserEmailVerification = `-- name: ClearUserEmailVerification :exec
UPDATE users SET email_verified_at = NULL, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ClearUserEmailVerification(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearUserEmailVerification, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password, fever_api_key, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $5)
RETURNING id, name, email, email_verified_at, password, remember_token,
    fever_api_key, two_factor_secret, two_factor_recovery_codes,
    two_factor_confirmed_at, created_at, updated_at
`

type CreateUserParams struct {
	Name        string     `json:"name"`
	Email       string     `json:"email"`
	Password    string     `json:"password"`
	FeverAPIKey *string    `json:"fever_api_key"`
	CreatedAt   *time.Time `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.FeverAPIKey,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Password,
		&i.RememberToken,
		&i.FeverAPIKey,
		&i.TwoFactorSecret,
		&i.TwoFactorRecoveryCodes,
		&i.TwoFactorConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, name, email, email_verified_at, password, remember_token,
    fever_api_key, two_factor_secret, two_factor_recovery_codes,
    two_factor_confirmed_at, created_at, updated_at
FROM users WHERE email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Password,
		&i.RememberToken,
		&i.FeverAPIKey,
		&i.TwoFactorSecret,
		&i.TwoFactorRecoveryCodes,
		&i.TwoFactorConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByFeverApiKey = `-- name: FindUserByFeverApiKey :one
SELECT id, name, email, email_verified_at, password, remember_token,
    fever_api_key, two_factor_secret, two_factor_recovery_codes,
    two_factor_confirmed_at, created_at, updated_at
FROM users WHERE fever_api_key = $1
`

func (q *Queries) FindUserByFeverApiKey(ctx context.Context, feverApiKey *string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByFeverApiKey, feverApiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Password,
		&i.RememberToken,
		&i.FeverAPIKey,
		&i.TwoFactorSecret,
		&i.TwoFactorRecoveryCodes,
		&i.TwoFactorConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, name, email, email_verified_at, password, remember_token,
    fever_api_key, two_factor_secret, two_factor_recovery_codes,
    two_factor_confirmed_at, created_at, updated_at
FROM users WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Password,
		&i.RememberToken,
		&i.FeverAPIKey,
		&i.TwoFactorSecret,
		&i.TwoFactorRecoveryCodes,
		&i.TwoFactorConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       int64  `json:"id"`
	Password string `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}

const updateUserPasswordAndFeverKey = `-- name: UpdateUserPasswordAndFeverKey :exec
UPDATE users SET password = $2, fever_api_key = $3, remember_token = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordAndFeverKeyParams struct {
	ID            int64   `json:"id"`
	Password      string  `json:"password"`
	FeverAPIKey   *string `json:"fever_api_key"`
	RememberToken *string `json:"remember_token"`
}

func (q *Queries) UpdateUserPasswordAndFeverKey(ctx context.Context, arg UpdateUserPasswordAndFeverKeyParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordAndFeverKey,
		arg.ID,
		arg.Password,
		arg.FeverAPIKey,
		arg.RememberToken,
	)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users SET name = $2, email = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile, arg.ID, arg.Name, arg.Email)
	return err
}

const updateUserTwoFactor = `-- name: UpdateUserTwoFactor :exec
UPDATE users SET two_factor_secret = $2, two_factor_recovery_codes = $3,
    two_factor_confirmed_at = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateUserTwoFactorParams struct {
	ID                     int64      `json:"id"`
	TwoFactorSecret        *string    `json:"two_factor_secret"`
	TwoFactorRecoveryCodes *string    `json:"two_factor_recovery_codes"`
	TwoFactorConfirmedAt   *time.Time `json:"two_factor_confirmed_at"`
}

func (q *Queries) UpdateUserTwoFactor(ctx context.Context, arg UpdateUserTwoFactorParams) error {
	_, err := q.db.Exec(ctx, updateUserTwoFactor,
		arg.ID,
		arg.TwoFactorSecret,
		arg.TwoFactorRecoveryCodes,
		arg.TwoFactorConfirmedAt,
	)
	return err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users SET email_verified_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, id)
	return err
}
